### ISSUE TITLE
Super-low-priority: Mappings pages should be unified into one page with tabs, consistent with providers

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#112]
Lowest priority in the whole backlog. Totally fine if we don't get to this

**Comment by mturley** [comment]
Maybe obsolete? (do we want to entirely remove the mappings pages)

**Comment by gildub** [comment]
@vconzola, what's the status on that one?

**Comment by vconzola** [comment]
@gildub Let's just let this one sit for a while longer. Post-beta, I want to talk to Fabien and Marco about getting rid of Mappings altogether and just having users create mappings as part of plan creation, especially if there will be additional parameters (e.g., volume mode and access mode) that need to be specified for mapped storage classes.
