### ISSUE TITLE
When oauth flow encounters an error it causes a redirect loop

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#153]
After my auth token had expired and my VPN had disconnected, I tried to reload my UI tab. It redirected to `/login`, which tried to fetch oauth metadata from the cluster, which obviously failed. This caused  redirect to our React-driven `/handle-login` route with an error param, but instead of displaying the error it triggered the normal "token is expired, redirect to login" behavior again and started a redirect loop between `/login` and `/handle-login`.

The `/handle-login` component needs to detect an `error` param and prevent the redirect to `/login` (which may be caused outside that component, not sure how to interrupt that).

**Comment by mturley** [comment]
This may be a dev environment only thing, or maybe it's unique to VPN being disconnected?

**Comment by gildub** [comment]
@mturley, VPN being disconnected falls into 504 error as gateway timeout. I'll try with an expired token in 24+ hours

**Comment by mturley** [comment]
It always seems to happen to me the next day after I had a valid token, but I thought it also happened once on the same day after a VPN disconnect. Maybe it's just the token.

**Comment by mturley** [comment]
I can't seem to reproduce this anymore. Maybe we fixed it when we switched everything to the proxy. Closing for now, maybe we'll need to reopen.
