### ISSUE TITLE
Visual bug: on medium-sized windows, some of our tables can stretch and overflow their container, making the last few columns unreachable

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#168]
Example, on the providers page:

![Screen Shot 2020-10-29 at 1 38 32 PM](https://user-images.githubusercontent.com/811963/97611177-33627980-19ec-11eb-8717-ddf4627875b0.png)

Some suggestions on how to handle it from UXD devs:

![Screen Shot 2020-10-29 at 1 40 54 PM](https://user-images.githubusercontent.com/811963/97611328-673d9f00-19ec-11eb-8163-1c883d24f88e.png)
![Screen Shot 2020-10-29 at 1 45 35 PM](https://user-images.githubusercontent.com/811963/97611823-0cf10e00-19ed-11eb-961b-c91e10baf1d3.png)

**Comment by seanforyou23** [comment]
The attached PR helps this, but at the end of the day there are simply too many columns to fit all at once in horizontal fashion when the viewport reaches certain sizes. We could either hide some less important columns when there isn't enough room or set an earlier breakpoint as mentioned in the attached thread. I suppose we could also consider moving some of this column data into compound expandable cells. Are any of these columns less critical to be in view at all times?

**Comment by mturley** [comment]
@vconzola see above. we should consider adjusting the columns of the VMware providers page in particular. Marking this issue as `needs-design` for followup.

**Comment by vconzola** [comment]
Why does the Endpoint column not truncate like the other columns. Fixing that would be my first choice. Also, it looks like an earlier breakpoint auto-hides the navigation. That's a good option too. If we do both of those things can we avoid f-ing with any of the other columns? Btw, have I mentioned I hate PF tables? It ridiculous that a design system for enterprise apps can't handle a table with seven columns because of the asinine font size and spacing rules.

**Comment by mturley** [comment]
Yeah, that's what the compact table variant is for which we could also try here, but it still has the font size issue. I like the look, but it definitely isn't as flexible as it should be

**Comment by seanforyou23** [comment]
I updated that PR to set these tables into "compact" mode, and also found another table with needed the truncation treatment - definitely looking better IMO. I can look into adjusting the various breakpoints, but it can have cascading effects so maybe I'll do that in a dedicated PR to make reviewing easier. Let me know if you see any issues!

**Comment by vconzola** [comment]
@seanforyou23 @mturley I agree it looks better in compact mode, but I don't understand how making that change eliminates the problem of the table overrunning the edge of the card? I thought compact tables just had reduced row heights. Do they do something to horizontal spacing as well?

**Comment by mturley** [comment]
I think there is less horizontal spacing between columns as well, yeah. The problem is just that the table's minimum width is dictated by the minimum widths of its columns, and that minimum is greater than the width of the breakpoint where the UI switches to mobile layout. We could widen that breakpoint but then we'll get mobile layout more often when the UI otherwise works fine at those medium window sizes.

So to reduce that minimum table width we can try a combination of reducing horizontal spacing (if compact mode does that) and/or moving columns to an expandable row body and/or making certain columns only appear at certain screen sizes.

**Comment by seanforyou23** [comment]
Yep, exactly. Was just trying to trim every pixel I reasonably could before making bigger layout/IA/content changes.
