### ISSUE TITLE
Add popover with reason for provider and host status

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#178]
Right now, the status column in the providers tables can just say Warning or Critical with no explanation of why. We should add a popover when you click on the icon to indicate the reason (I assume.. can you confirm this is the right interaction @vconzola ?)

![Screen Shot 2020-11-02 at 11 52 19 AM](https://user-images.githubusercontent.com/811963/97895590-fa831700-1d01-11eb-98b0-79b39624b93f.png)

**Comment by vconzola** [comment]
@mturley Mockups (slide 14) show it as a tooltip. I guess it depends on how much information we need to show about the reason for the condition. If it's just a line of text use a tooltip.

**Comment by mturley** [comment]
@vconzola ah, sorry I missed that. Also I think I meant tooltip, I keep confusing the two because in PF3 we just had Popover.

**Comment by mturley** [comment]
Need to look at the message field on the provider's conditions and make sure that is meaningful

**Comment by mturley** [comment]
IMO it would be really nice to get this into beta, when you see "Critical" on a provider or a host and you can't tell why, it's a bit frustrating. @vconzola  @fdupont-redhat do you think it's appropriate to prioritize this?

**Comment by vconzola** [comment]
@mturley If you can get it in, I agree it would be a nice UX improvement. Do you have what you need to know why the status would be warning or critical? Also, Critical sounds a little extreme to me. I can't imagine what would make a provider or host status critical unless there was smoke billowing from it.

**Comment by mturley** [comment]
Haha, you'll have to take that one up with Jeff. But yeah I think I have a message in there to display, I'll check and follow up.

**Comment by mturley** [comment]
Moving this into beta-land, I'll try and get it implemented before the end of the week.
