### ISSUE TITLE
VM migration details page: center VM row text vertically

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#179]
To make this table a little cleaner, let's use some CSS to vertically center the text of the rows in `VMMigrationDetails` which are currently top-aligned (not sure what the best solution is).

![Screen Shot 2020-11-02 at 11 59 14 AM](https://user-images.githubusercontent.com/811963/97896549-3a96c980-1d03-11eb-9d5e-771aa8c3caf2.png)

**Comment by mturley** [comment]
Removing the compact table piece of this, I assumed that's what was meant by the feedback for #181.

**Comment by gildub** [comment]
@mturley, after I couldn't find reference documentation about how to use `columnTransforms` to be effective.
Then I tried some css rules by directly passing classes through IRows and ICells props.
This is incredibly time consuming and frustrating.

**Comment by mturley** [comment]
@gildub don't worry about it then. It's not important enough to waste time on. I'll take a look later
