### ISSUE TITLE
A started migration plan doesn't display spinner after refreshing page. 

### ISSUE THREAD

**Issue by gildub** [konveyor/forklift-ui#183]
After creating a mig plan, once initialized, the start button will be displayed. 
Once 'Start" has been clicked the button is replaced with Spinner.
Meanwhile if the page is left then returned too (while the migration is still getting created) the Spinner is not visible, only the Start button is.

**Comment by mturley** [comment]
Hmm. I guess instead of local state to indicate that a plan is being started, we need to query the Migration CRs and see if there is one matching that plan? That's a bit annoying, but yeah probably a good idea

**Comment by mturley** [comment]
I believe this was fixed in https://github.com/konveyor/forklift-ui/pull/501.
