### ISSUE TITLE
How to handle mappings that reference any storages/networks that have been removed?

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#208]
We should make sure none of our UI breaks if the resources referenced in a mapping (whether part of a plan or not) no longer exist. They are inventory resources, so we can't automatically delete mappings when they are removed via ownerReferences, so we'll probably need something to indicate when rendering/editing them that they are broken.

**Comment by mturley** [comment]
Should we have validation messages on mappings like we have for VMs?

**Comment by mturley** [comment]
Same here @vconzola , this is needs-design. Might be easiest to just add a Status column to the mappings tables like we have for providers and plans.

**Comment by vconzola** [comment]
@mturley Agree - a Status column is probably the most straightforward way to show this. Are you thinking Ready / Not Ready as the possible status values?

**Comment by mturley** [comment]
Maybe, to be consistent. I'm not sure I can know for sure if the associated resources themselves are actually ready though, just whether they exist. I mostly want to point out "broken/orphaned" mappings that map things that no longer exist.

**Comment by vconzola** [comment]
For consistency, I was thinking the mapping itself can be defined as Ready / Not ready. If it's "not ready", can it be made ready again if the storages or networks are re-added? I know we talked about this for IMS, but it wasn't possible because when resources were re-added they were given a different id in CloudForms. Hence, those plans truly were orphaned. Not sure if that's the case here?

**Comment by mturley** [comment]
It sounds like based on this morning's meeting that once it's "not ready" the only way to make it ready again would be to edit it and remove the broken items. I was initally just going to prevent it from being edited at all if it's broken though, so we don't get errors where it can't find things in the inventory. The problem with making editing possible is that once an item doesn't exist in the inventory we can't look up its name (only the id is stored in the mapping) so we can't even show what was broken.

**Comment by mturley** [comment]
In fact, a broken mapping will even have its expanded view in the table broken since we can't look up those names. I may just have to display "missing" in place of the invalid items

**Comment by mturley** [comment]
Status column text should be "OK" vs "Invalid" per @vconzola . Invalid should have a tooltip "One or more mapping resources no longer exist. Delete the mapping and recreate with valid resources"

**Comment by mturley** [comment]
I'm thinking this would be good to get into the beta (at least prioritize over other issues marked for post-beta) because it's the last obvious case I can see where the user could break the UI by messing with provider resources.
