### ISSUE TITLE
Select VMs step of wizard: in smaller screen sizes, the filter dropdown has some strange behavior

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#218]
It has a weird transparent background:

![Screen Shot 2020-11-13 at 3 46 21 PM](https://user-images.githubusercontent.com/811963/99119760-baf0e080-25c7-11eb-9957-1e8e0133537b.png)

Also, if you click the X in the text field, instead of just clearing the text field it also shows a filter chip that was otherwise hidden (should appear immediately)

**Comment by gildub** [comment]
This occurs also with PlansPage filter.

![filter-resize-plans](https://user-images.githubusercontent.com/1901741/100335713-93d9dc00-2fd5-11eb-9371-d30b5f1d1e61.png)

The filter seems to have several issues in smaller screen size:
- Looks like issues with the breakdown points definitions
- Transparent background is confusing as it mixes with the page data

**Comment by mturley** [comment]
Super low priority since I don't think we will claim to support mobile devices for MTV. But post-beta, we should see if this is also an issue in upstream PF.
