### ISSUE TITLE
Mappings: Filter target storage classes by what is compatible with kubevirt

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#248]
From a discussion with @fdupont-redhat, it turns out that only certain storage classes will be compatible with kubevirt, so once we can determine which ones are valid we should filter the available mapping choices.

Marking as `blocked` until we have the API resource to determine this filter logic.

**Comment by mturley** [comment]
We can hard-code the list of valid target storage classes in `virtMeta.json`. Follow up with @fdupont-redhat on which storage classes we should start with.

**Comment by mturley** [comment]
Also needs to be shared with the controller, so maybe it should be in a config map or other shared resource.

**Comment by gildub** [comment]
@fdupont-redhat, could you please provide an initial list of storage classes ?

**Comment by gildub** [comment]
Update: https://github.com/konveyor/forklift-controller/issues/77

**Comment by mturley** [comment]
Just had a meeting with @jortel and @fdupont-redhat about this, it seems what we need to do is load the Provisioner CRs, which are associated with storage classes. If a storage class does not have a provisioner, it's not compatible.

**Comment by mturley** [comment]
Removing the blocked label as we have a path forward here now.

**Comment by mturley** [comment]
@vconzola I'm wondering if instead of totally removing storage classes that are not compatible, we should disable them with a tooltip explaining that they aren't compatible. Does that make sense to you?

**Comment by mturley** [comment]
From a discussion with @vconzola we decided to disable incompatible storage classes with a tooltip rather than remove them.
