### ISSUE TITLE
Identify dependent resources and mark things as invalid defensively instead of failing when the dependents are missing

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#249]
This came out of discussion around https://github.com/konveyor/virt-ui/issues/207. If for example we have a plan or a mapping and the provider(s) referenced in them are missing, we may have an error when we try to display the plan/mapping. We need to make sure we handle this gracefully, and identify all cases where this may be an issue.

**Comment by mturley** [comment]
As part of identifying these cases we may want to see if there are any other places where we need to add `ownerReferences` (see kubev2v/forklift-console-plugin#129)

**Comment by gildub** [comment]
- [ ] Providers
- [ ] Mappings
  - [ ] Network
  - [ ] Storage
- [X] Plans
  - [X] Migrations

**Comment by mturley** [comment]
I believe this is resolved now. Will reopen if we find any more cases of missing ownerReferences or query dependencies.
