### ISSUE TITLE
[BZ#1899437] Add "Openshift virtualization" provider form improvements

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#250]
https://bugzilla.redhat.com/show_bug.cgi?id=1899437

See BZ for details.

@vconzola

**Comment by mturley** [comment]
@vconzola when you get a chance we should review Avital's suggestions here, Fabien marked the BZ for beta.

**Comment by vconzola** [comment]
@ibolton336 I definitely agree with her points 2 and 3. Number 1, I'm not so sure about. i thought the user had to specify the name of an OpenShift cluster that will be an MTV provider - not just an identifier name to be used in MTV. 

@mturley @fdupont-redhat Is a cluster name needed in the provider creation form, or is the URL enough?

**Comment by mturley** [comment]
That may be a question for @jortel . Come to think of it though I think maybe just the URL needs to match.

**Comment by mturley** [comment]
@vconzola @ibolton336 I just checked with Jeff, he confirmed that this cluster name doesn't need to match anything in the actual cluster, it's just an identifier for MTV. Only the URL matters. So I think it's fair to rename the field to "name" here.

**Comment by vconzola** [comment]
@mturley Thanks for checking. "Name" it is.
