### ISSUE TITLE
VMware provider hosts page: display subnet masks for migration networks

### ISSUE THREAD

**Issue by gildub** [konveyor/forklift-ui#260]
Following up on https://github.com/konveyor/virt-ui/pull/244, I think displaying the name and the IP address of each network interface under the column "Network for migration data transfer" could be improved.

~~Why not just call the column "Physical network interface name and IP address" or equivalent?~~

The main driven behind is because IP addresses are host address and not network ranges and could be confusing for the user.

(Edit by @mturley): we now have subnet masks for each migration network, we can display them next to the IP address in slash notation (see https://github.com/konveyor/forklift-controller/pull/170#issuecomment-785426258).

**Comment by mturley** [comment]
Renaming this issue now that https://github.com/konveyor/forklift-controller/pull/170 gives us the ability to display subnet masks. See @fdupont-redhat 's comment here: https://github.com/konveyor/forklift-controller/pull/170#issuecomment-785426258
