### ISSUE TITLE
Determine and show the default migration network for hosts before they are configured

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#292]
Related RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1908034

From the discussion here: https://github.com/konveyor/virt-ui/pull/244#issuecomment-731192433

Right now there is no way for the UI to know what network will be used for a host unless it was specified by the user (the default is determined in the backend at migration time), so we just display (default) and no other information. We also can't specify in the list of networks to choose from which is the default.

If there is some way of identifying from vSphere which one is the default network, we should use that to display details in the table before a host is configured, and distinguish the default network in the network selection modal.

Relevant chatter from Slack:

@jortel :
> I wonder if it's simple as always the one named: "Management Network"?

@fdupont-redhat :
> this will be the network of the hostname / IP address of the host in vSphere inventory. So, it's probable that it could be determined by some network calculation. Hacky and not sure how accurate it will be.

**Comment by mturley** [comment]
This will become possible once https://github.com/konveyor/forklift-controller/issues/120 is addressed.

**Comment by fdupont-redhat** [comment]
@mturley, indeed https://github.com/konveyor/forklift-controller/issues/120 will avoid the _hacky_ aspect.

**Comment by mturley** [comment]
@fdupont-redhat I was implementing #427 which just assumes the default network is the one named "Management Network", and I figured if we're making that assumption for that use case I should just go with it for this one. So that PR will close this issue as well. If you think that's not a sufficient way to determine the default network, we can reopen this issue.

**Comment by fdupont-redhat** [comment]
The network name is not enough, since it can be renamed in VMware. I think it should be an inventory attribute.

**Comment by mturley** [comment]
ah, ok. maybe #427 should not be merged at all then until we have that attribute. Sorry, I just asked the same question in the BZ.
