### ISSUE TITLE
[BZ#1907733] While editing resources, save button is enabled even when no changes are made

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#329]
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1907733

The BZ refers to providers but this applies to all of our editing forms. See my comment in the BZ for implementation notes.

**Comment by gildub** [comment]
@mturley,

As you commented in BZ, using a state flag makes me wonder if we're not better of reimplementing `useEditProviderPrefillEffect` so the form could rely on `setIsTouched`.

**Comment by mturley** [comment]
@gildub I think the right solution here might require a change to `useFormState`. I think if we keep track of a form-level `isTouched` and only consider the form `isValid` if it has been touched, and then don't call `setIsTouched` at all in the prefill effects, that would fix it. In theory we could use isDirty, but a form prefilled asynchronously is going to be dirty (to solve that we'd have to somehow prevent certain setValue calls from setting isDirty on the fields).

Either way I think we need a lib-ui change.

**Comment by mturley** [comment]
The only reason I was calling `setIsTouched` in the prefill effect was so validation errors would appear immediately on prefill, but in theory there shouldn't ever be validation errors from prefilled values if they were valid when the CR was created.
