### ISSUE TITLE
Add "expand/collapse all" control in the header of the leftmost column of the select VMs table in step 2 of the plan wizard.

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#36]
Similar to #35, we will need a change in PF to support this since we can't modify the header of that column (it's generated by the `expandable` transform in `Table`). Will open an issue there and follow up here.

Once it's available, [as noted here](https://github.com/konveyor/virt-ui/pull/21#issuecomment-689722506) we can use the `selectAll` and `areAllSelected` values from `useSelectionState` to drive this button, and it should use the `<AngleRightIcon>` and `<AngleDownIcon>` icons depending on its state.

**Comment by mturley** [comment]
Upstream issue to track: https://github.com/patternfly/patternfly-react/issues/4798

**Comment by mturley** [comment]
The upstream issue was closed because it is moving back to the design stage. It sounds like they are talking about making it a toolbar button above the table though, instead of in the table header. We could probably implement it like that today, if you want to @vconzola .

**Comment by vconzola** [comment]
@mturley It's up to you. Definitely a nice-to-have for beta if you just want to wait until the design is finalized in PF.

**Comment by mturley** [comment]
sure. I'll leave this issue open until I see it finalized in PF, we can wait.

**Comment by mturley** [comment]
This was concluded in PF back in October, the decision was to support it as a toggle in the toolbar above the table. See this demo: https://github.com/patternfly/patternfly-react/pull/5030
