### ISSUE TITLE
Add the ability to unset the migration network

### ISSUE THREAD

**Issue by fdupont-redhat** [konveyor/forklift-ui#421]
Once a migration network has been selected for a VMware host, it is only possible to select another network as migration network, not reset to no migration network.

It is possible that the users have invalid credentials and that until they retrieve valid credentials they want to fall back to the default behavior, i.e. connect to vCenter and use the management network. And this is currently not possible.

From a technical point of view, this would mean deleting the Host CR.

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1929050

**Comment by mturley** [comment]
Had a discussion with @vconzola . Since we already have "management network" as a choice in the dropdown there, the plan is to just delete the CR if that option is selected. The credentials fields will be disabled in that case.

**Comment by mturley** [comment]
Blocked by https://github.com/konveyor/forklift-controller/issues/120.
