### ISSUE TITLE
Migration plan wizard: source/target provider fields. RFE?

### ISSUE THREAD

**Issue by apinnick** [konveyor/forklift-ui#428]
In the Migration Plan wizard, General screen, I was wondering whether we should rethink the names of the source provider and target provider fields in the future.

If I, as a user, were to select a "source provider", I would expect to see VMware or RHV. I would expect the "target provider" to be OCPv.

Would a term like "source data center" / "target data center" make more sense? "Provider" does not seem to be the right term in this context.

![image](https://user-images.githubusercontent.com/31725355/108177451-efff5880-710b-11eb-957c-c2778538918a.png)

**Comment by mturley** [comment]
We use "provider" pretty universally to refer to the environment being migrated from/to. We'd have to examine some text in other places as well. cc @vconzola

**Comment by vconzola** [comment]
@apinnick Not sure I understand. The list contents for Source provider and Target provider are the names of the VMware and OCPv providers from the Providers page. As Mike mentioned, if we changed it here we'd have to rename the Providers page and other places "providers" is used in the UI.

**Comment by mturley** [comment]
"Provider" is also the term used by CloudForms for these same resources, which is why we called them that in IMS.

**Comment by apinnick** [comment]
> "Provider" is also the term used by CloudForms for these same resources, which is why we called them that in IMS. @apinnick I would call what you're expecting to be a "Provider" a "Provider Type".

OK, that makes sense. I'll close this issue.
