### ISSUE TITLE
Improved text for migration network tooltip

### ISSUE THREAD

**Issue by apinnick** [konveyor/forklift-ui#449]
![image](https://user-images.githubusercontent.com/31725355/111317517-e87c9200-866c-11eb-9c46-deac976db781.png)

Suggested text:

The default migration transfer network is determined by the target provider and the namespace. The migration network defined for the OpenShift Virtualization provider is the default. You can select a different network for this migration plan.

**Comment by mturley** [comment]
@apinnick I think the suggested text fails to explain one of the important details that is strange about this behavior: if the user-specified default on the provider does not exist in the target namespace, it cannot be used and the pod network will be used instead. We were trying to express that with the "If possible" phrasing.

Maybe this works:

> The default migration transfer network is determined by the target provider and the namespace. The migration network defined for the OpenShift Virtualization provider will be used if it exists in the selected namespace. You can select a different network for this migration plan.

**Comment by mturley** [comment]
cc @vconzola

**Comment by apinnick** [comment]
> @apinnick I think the suggested text fails to explain one of the important details that is strange about this behavior: if the user-specified default on the provider does not exist in the target namespace, it cannot be used and the pod network will be used instead. We were trying to express that with the "If possible" phrasing.

I'm confused by the choice of the "if possible" phrasing.

In the comments on the [mockup (slide 7)](https://docs.google.com/presentation/d/1QzhcsDKiYDM7dFFPKS82uDsemvZrglp4YHWU8wE5Smw/edit#slide=id.gb441748087_0_26), it sounds like the UI was designed to downplay the option of changing the network (hence, "if possible").

However, the [epic](https://issues.redhat.com/browse/MTV-18) says that the default networks (admin for VMware, pod for OCP) lead to poor performance. So shouldn't we be encouraging the user to change the networks from the default?

> 
> Maybe this works:
> 
> > The default migration transfer network is determined by the target provider and the namespace. The migration network defined for the OpenShift Virtualization provider will be used if it exists in the selected namespace. You can select a different network for this migration plan.

**Comment by mturley** [comment]
I think the confusion is in the word "default". The original defaults that are used with no user intervention are poor, yes, but there is a "user-specified default" they can set right in MTV on the providers page, and if that is present AND it is a network that exists in the target namespace, it is used instead of the poor-performance default. Additionally, the user can override it here for the specific plan. Yes... confusing

**Comment by apinnick** [comment]
> I think the confusion is in the word "default". The original defaults that are used with no user intervention are poor, yes, but there is a "user-specified default" they can set right in MTV on the providers page, and if that is present AND it is a network that exists in the target namespace, it is used instead of the poor-performance default. Additionally, the user can override it here for the specific plan. Yes... confusing

I didn't know about the network also having to be in the target namespace. Now I get it. This will require some explaining in the docs as well.

Looking at your suggested text:

> The default migration transfer network is determined by the target provider and the namespace. The migration network defined for the OpenShift Virtualization provider will be used if it exists in the selected namespace. You can select a different network for this migration plan.

Is the first sentence repeating the second sentence? That is, the default network is used if the user has defined it for the provider and if the network is in the target namespace. And if not, well, tough luck....

What do you think of this version?

The default migration network defined for the OpenShift Virtualization provider is used if it exists in the target namespace. You can select a different network for this migration plan.

**Comment by mturley** [comment]
I think that works. Should we also add a sentence "Otherwise, the pod network is used"? Also, this phrasing implies that there is definitely a default defined on the provider, which there may not be (the user would have had to do that).

What about this?

> If a default migration network is defined for the OpenShift Virtualization provider and it exists in the target namespace, it is used. Otherwise, the pod network is used. You can select a different network for this migration plan.

**Comment by apinnick** [comment]
> I think that works. Should we also add a sentence "Otherwise, the pod network is used"? Also, this phrasing implies that there is definitely a default defined on the provider, which there may not be (the user would have had to do that).

There is always a default defined on the provider, even if it is not user-defined. If the user defined a default, it is the new migration network. If not, it is the out-of-the-box pod network. But I suppose we could make it more explicit, so the "Otherwise..." sentence works for me.

> 
> What about this?
> 
> > If a default migration network is defined for the OpenShift Virtualization provider and it exists in the target namespace, it is used. Otherwise, the pod network is used. You can select a different network for this migration plan.

**Comment by mturley** [comment]
ok. so I'll go with your last suggestion plus the Otherwise.

> The default migration network defined for the OpenShift Virtualization provider is used if it exists in the target namespace. Otherwise, the pod network is used. You can select a different network for this migration plan.
