### ISSUE TITLE
"Add provider" modal - "Certificate SHA1 Fingerprint" field should be called "SHA-1 fingerprint"

### ISSUE THREAD

**Issue by apinnick** [konveyor/forklift-ui#452]
![image](https://user-images.githubusercontent.com/31725355/111443364-fafcd700-8711-11eb-9072-c0474f47e91f.png)

The "Hostname or IP address" field is required but does not display the validation message "... is a required field" when it is skipped.

Just noticed another small fix: "Fingerprint" should be lower case.

Suggestion about the "Certificate SHA1 Fingerprint" label. It's a little odd, because it is actually the SHA-1 (this is how VMware always styles the algorithm) fingerprint of the SSL certificate of the ESXi host. "Certificate" does not quite work as an adjective in this context.

You might want to change this to "SHA-1 fingerprint" because all of these fields are for the VMware ESXi host.

**Comment by mturley** [comment]
@apinnick on my end the "Hostname or IP address" field is behaving just like the other fields. You have to focus the field and then move away from it while it is still blank/invalid to see the message. This is just because the Add button isn't enabled until the form is valid, and we don't want errors appearing until the user does something wrong. That's why we have the red asterisks on required fields.

I'll let @vconzola weigh in on the phrasing of the fingerprint field. I agree we should style it as "SHA-1" but I believe we originally didn't have the word Certificate in there and someone requested it (I can't remember why).

**Comment by apinnick** [comment]
> @apinnick on my end the "Hostname or IP address" field is behaving just like the other fields. You have to focus the field and then move away from it while it is still blank/invalid to see the message. This is just because the Add button isn't enabled until the form is valid, and we don't want errors appearing until the user does something wrong. That's why we have the red asterisks on required fields.

That's exactly what I did with the Hostname field-- click in it, then move to another field. I never saw the message for that field. I was using the demo site. I tried several times. Are you saying that the reason I did not see the message is because the Add button is disabled for the demo?

If you were unable to reproduce my bug, I'll take your word for it.

> 
> I'll let @vconzola weigh in on the phrasing of the fingerprint field. I agree we should style it as "SHA-1" but I believe we originally didn't have the word Certificate in there and someone requested it (I can't remember why).

I would be interested to know the reasoning behind adding Certificate. Thanks.
"fingerprint" should be lower case.

**Comment by vconzola** [comment]
@mturley @apinnick I honestly don't remember who gave me the text for the fingerprint field, but I put in the mockups whatever I was told. If it makes more sense without "certificate", that works for me.

**Comment by apinnick** [comment]
> Which demo URL were you using, and what browser? On the latest main branch (http://konveyor-forklift-ui-preview.surge.sh/) it's working correctly for me in Chrome and Firefox:

Now I see it! I am using the same browser that I used before, Firefox. It's possible that I was using the URL for a feature branch and not main. Next time I will check what branch I'm on. So you can disregard the validation message part.

"SHA-1 fingerprint" would be great. Thanks.

Comment that is unrelated to the UI: I noticed that the Provider CR yaml is calling it a "thumbprint". <sigh> I should submit an issue for that but it will be low priority. I checked the VMware documentation to verify that fingerprint is the correct term.

Thanks again!

**Comment by mturley** [comment]
I think `thumbprint` was chosen because there's something under the hood that calls it that and they wanted to be consistent in the code. We always call it a fingerprint in user-facing places.

**Comment by mturley** [comment]
Ah, forgot to change the title of the field (was closing because of the validation message). Reopening.
