### ISSUE TITLE
Fix logic for StatusCondition severity and icons when there are Required and/or Advisory conditions

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#457]
As seen in this screenshot, conditions on a provider are not always assigned the correct severity in the UI.

![Screen Shot 2021-03-11 at 12 40 48 PM](https://user-images.githubusercontent.com/811963/111806376-48ab4800-88a8-11eb-97ae-a341f6780a2f.png)

I need to double check the logic around Required conditions in particular, since the `category` property is Required rather than a severity value, so the severity must be inferred from other properties on the condition.

cc @jortel @vconzola

**Comment by mperezco** [comment]
During the review meeting the word "Processing" was suggested.

**Comment by mturley** [comment]
@vconzola what do you think for "Processing" if there are required conditions that are incomplete like "Loading the inventory"? We've also used "Pending" in this column in some places (waiting for conditions to appear when you create a plan)

**Comment by vconzola** [comment]
@mturley If we use "Pending" in other places I think we should be consistent. Also, to me pending implies we're waiting on an external process to complete before we can take action vs. processing which implies that the thing we want to take action on is already doing something. In this case (and correct me if I'm wrong) the provider is waiting on the external validation service to complete so it can be in a ready to migrate state.

**Comment by mturley** [comment]
That's correct. In the case of CRs with Required conditions that are not satisfied, we're just waiting on something in the controller or validation service to mark the CR as Ready before it can be used.

**Comment by mturley** [comment]
Hmm, actually, I'm not certain about that. I'll double check with Jeff.
