### ISSUE TITLE
[BZ#1942135] Breadcrumb bar on VMware Hosts page conflicts with page title

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#460]
https://bugzilla.redhat.com/show_bug.cgi?id=1942135

From the usability study (https://docs.google.com/presentation/d/1_GdHUjugbX-CB_P3u12qQmfDbSO99Fo_QE0g1CWPfH8/edit?ts=6058cc49#slide=id.gc70a21fdbb_0_36)

> The “Hosts” breadcrumb hierarchy was confusing
> * One user had difficulty interpreting the “Hosts” breadcrumb, where it showed “host_name > Hosts” rather than “Hosts > host_name”. The breadcrumb was also in direct conflict with the page title.
> * Consider adjusting the order of the hosts breadcrumb to reflect the hierarchy. 

![Screen Shot 2021-03-22 at 1 07 50 PM](https://user-images.githubusercontent.com/811963/112029425-9ecdf480-8b0f-11eb-835c-4c895b14d499.png)

As described, the issue is not quite accurate - the breadcrumb bar does not show a "host_name > Hosts", it shows "provider_name > Hosts". The page title however shows "Hosts - provider_name", so I think the last item in the breadcrumb bar should show this instead of having Hosts be a separate item.

"Providers > VMware > Hosts - provider_name"

cc @vconzola

**Comment by vconzola** [comment]
@mturley The breadcrumb should show the path the user traversed to get to the current page. So Providers > VMware > vmware_provider_name > Hosts is correct with VMware being a link to return to the previous page. I think the only thing we need to change is to get rid of the provider name in the page heading. User can refer to the breadcrumb if they can't remember which provider they're looking at. PF would say we don't even need a page heading, but I don't like showing tables without some context.

**Comment by mturley** [comment]
Ok, sounds good. Thanks Vince.
