### ISSUE TITLE
[BZ#1943373] General step of wizard: usability issues with creating a new target namespace

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#463]
https://bugzilla.redhat.com/show_bug.cgi?id=1943373

Observations from the usability study:
* When typing in the target namespace field (typeahead search), one of the options is "Create" which can be clicked to create a namespace from the search text instead of selecting an existing one.
* Clicking away from the field without choosing a dropdown option will clear the field -- this was unexpected and frustrating because users assumed it behaved like a normal text input field. It's not obvious that you need to click on the dropdown item to retain the name you type.
* Users also tried to press Enter to select the 'Create' option which doesn't work either.

This may be an issue in the way the PatternFly Typeahead Select component works. But if we can set an event handler on the change event of that search text field, we could have the form state retain whatever they type in there unless they click one of the options.

@vconzola, if the user just types something in the field and clicks away, do you think it is obvious enough that a new namespace will be created? Should we maybe add some text that appears below to indicate that the namespace in the field does not exist and will be created?

**Comment by vconzola** [comment]
@mturley I'm going to answer your question with a question. Two questions, actually. When does the Next button get enabled? And, when does the new namespace actually get created - on Next or on wizard completion?

**Comment by mturley** [comment]
@vconzola the Next button is enabled when all required fields have a value. In this case, the target namespace field is not considered to have a value until one of the dropdown menu options is selected (including "Create") but with the proposed change, it would have a value as soon as the user starts typing in it. Also, I'm realizing I need to add validation to the custom namespace name to make sure it's a valid k8s resource name.

**Comment by mturley** [comment]
Also, the namespace gets created when the user submits the wizard. They can go back and change it before then.

**Comment by vconzola** [comment]
@mturley OK...a couple things. First, since the namespace doesn't get created until the plan is completed, would it make sense to just put the text informing the user the namespace will be created in the review step? I think it's obvious enough when the user types in the field what will happen that we don't need to say it again in the wizard step 1 form. Second, if the user types in a new namespace we should show pod_network as the migration network but not give them the option to change it since it won't be configured to use any other networks.

**Comment by mturley** [comment]
@vconzola that all makes sense to me, will do.

**Comment by mturley** [comment]
Note to self: Review step indication that a namespace will be created: “This is a new namespace that will be created when plan is saved.” Either as a line under the namespace or an info icon with popover.

**Comment by mturley** [comment]
Retargeted for 2.1.0, removing priority label

**Comment by mturley** [comment]
Note: another issue to consider here: because the field is right at the bottom of the form, on some screens it gets cut off by the wizard footer when it opens, so it might not be possible to see the "Create" option right away. This is probably part of the user confusion. @vconzola suggested maybe we automatically scroll to the bottom when the dropdown opens, but we'd need to limit the height of the dropdown and that may introduce its own weird UX if the user has a lot of namespaces to scroll through. Another option would be to make it possible for the dropdown to pop out and display on top of the rest of the page contents (everywhere in the UI, would be nice) but that may not be possible in a scrollable container. Need to investigate.

**Comment by vconzola** [comment]
This issue is being discussed in patternfly-react: https://github.com/patternfly/patternfly-react/issues/5502. I think we should wait to see their conclusion before doing anything else with this.

**Comment by mturley** [comment]
Thanks @vconzola. Glad that's already in motion.

**Comment by mturley** [comment]
Following up after PF upgrades:
* The issue above with pressing the Enter key has been fixed, the new namespace typed in will be retained when pressing Enter.
* To get the desired behavior of retaining the value when clicking away from the field, we need to pass the new `isInputValuePersisted` into the Select. See https://github.com/patternfly/patternfly-react/issues/5502
* To address @vconzola 's comment here: https://github.com/konveyor/forklift-ui/issues/463#issuecomment-805110886 we should hide the "Select a different network" link if the value of `form.values.targetNamespace` is not present in the `namespacesQuery.data`.

Addressing the above points will close this issue.
