### ISSUE TITLE
[BZ#1942080] Improve instruction text on the Filter VMs step of the wizard

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#466]
https://bugzilla.redhat.com/show_bug.cgi?id=1942080

In the usability study, users were confused by the tree-view selection on the Filter VMs step of the wizard. They thought they were selecting VMs on this step and tried typing VM names in the search box rather than hosts/datacenters/folders.

@vconzola have we already designed the necessary changes here for GA?

**Comment by vconzola** [comment]
@mturley We haven't. How about, "Select VMware hosts or folders where the VMs you want to migrate are located." That sounds a little awkward... Let me check with Abby/Alana and see what they think.

**Comment by mperezco** [comment]
@vconzola @mturley shouldn't we use a non-specific sentence (so it works with other providers).
Something like: "Select the hosts and folders where the VMs to be migrated are located"

**Comment by vconzola** [comment]
@mturley @mperezco I met with one of our content experts and here's what we came up with. Change the page header to "Filter by VM location" and the subtext to "Refine the list of VMs selectable for migration by cluster and host, or folder." Sound OK to all y'all.

**Comment by mturley** [comment]
Works for me.

**Comment by mperezco** [comment]
+1
