### ISSUE TITLE
[BZ#1942128] Display amount of data copied with decimal places or MB precision

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#467]
https://bugzilla.redhat.com/show_bug.cgi?id=1942128

Noticed in the usability study. Since we round to the nearest GB when displaying the amount of data copied in a migration, users were not sure if anything was happening while the status displayed 0 GB copied. The API gives us this data as MB, we should increase the precision of the number we display.

@vconzola should this still be in GB but with decimal places, or do you want me to show it in MB? If GB with decimal, how precise should it be / how many decimal places?

**Comment by vconzola** [comment]
@mturley How about two decimal places and leave as GB? I would think even with a slow network that level of granularity would change with every poll. Do you agree?

**Comment by mturley** [comment]
That sounds right to me. Will do.

**Comment by mperezco** [comment]
GB with two decimals sounds nice to me too.

+1
