### ISSUE TITLE
[BZ#1944415] Usability: confusion around buttons and tooltips in create mapping form

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#488]
https://bugzilla.redhat.com/show_bug.cgi?id=1944415

Some users in the usability study were unsure of the purpose of the Add button on the create mapping form, which inserts another source/target pair in the mapping editor. Some of the confusion was because of the fact that you have active "Add and "Create" buttons on the same page, which both sound like the primary verb on the page.

Some of the confusion is coming from the fact that there can be two different tooltip messages explaining why this button is disabled. When the user hasn't selected a source in all their mapping pairs yet, it shows this one:

<img width="451" alt="Screen Shot 2021-03-26 at 4 57 31 PM" src="https://user-images.githubusercontent.com/811963/112691949-7833f480-8e54-11eb-9151-5543b16cc6f8.png">

And when there are no more sources available to choose from it shows this one:
<img width="438" alt="Screen Shot 2021-03-26 at 4 51 18 PM" src="https://user-images.githubusercontent.com/811963/112691740-24291000-8e54-11eb-9ef7-0b0507b5349d.png">

The user wondered why the text is different here for storage and network mappings, when in fact it is not. The difference is that there was only one source network to be mapped and there were multiple source datastores, so the network mapping builder initially is already in that latter state before any choices have been made, so it shows the second tooltip.

See usability study review slide 19: https://docs.google.com/presentation/d/1_GdHUjugbX-CB_P3u12qQmfDbSO99Fo_QE0g1CWPfH8/edit?ts=6058cc49#slide=id.gc70a21fdbb_0_104

@vconzola do you think we can improve this text or is this a wontfix?

**Comment by vconzola** [comment]
@mturley I think this is a case where it might be better to hide the Add button when a new mapping can't be created.

**Comment by mturley** [comment]
Yeah, that makes sense to me. Do you mean hide it in both cases I outline above? Or only when there are no more sources remaining (still leave it with the first tooltip shown above if you leave something blank but there could be more sources to add)?

**Comment by mturley** [comment]
Note to self: we decided to hide the button only in the case where you have blank source/target fields, and leave the disabled button when there are no more sources remaining.
