### ISSUE TITLE
Replace @patternfly/react-icons imports with direct deep-path imports to reduce bundle size

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#55]
According to @redallen we should be importing our icons like this:

```ts
import CogIcon from '@patternfly/react-icons/dist/js/icons/cog-icon';
```

instead of:

```ts
import { CogIcon } from '@patternfly/react-icons';
```

As-is, we're bundling and shipping all of those SVG icons in our app no matter which ones we use.

We should also add https://github.com/patternfly/patternfly-react/tree/master/packages/eslint-plugin-patternfly-react to catch these issues in the future.

**Comment by gildub** [comment]
@mturley,
The recommend way doesn't work.
I tried with current @patternfly/react-icons version and latest 4.7.11.
I've created an issue on Pattern Fly project: https://github.com/patternfly/patternfly-react/issues/5028

**Comment by mturley** [comment]
Thanks @gildub . Not sure what changed, I think this way of importing was working for a few icons in mig-ui.

**Comment by mturley** [comment]
Also I agree it would be optimal to continue importing them the way we are, but we definitely don't want to bundle the entire icons package with our apps. They bundle the entire Font Awesome collection in there, it's huge.

**Comment by gildub** [comment]
@mturley, following up on this issue, 

Using the shaking tree now works for `@patternfly/react-icons`, adding a PR to address those.

I was wondering too about the bundle size from other icons we import from `@patternfly/react-core` and `@konveyor/lib-ui`.
For example `src/app/NotFound.tsx` uses `EmptyStateIcon` from react-core.
Or `StatusIcon` from lib-ui.
I don't think there are issues because they're imported as React components.

**Comment by mturley** [comment]
`StatusIcon` from lib-ui should probably be refactored to use the tree-shakeable imports itself as well. I didn't realize `EmptyStateIcon` was coming from react-core, if that's available in react-icons maybe we should be importing it from there instead.

**Comment by mturley** [comment]
Oh, I forgot about `EmptyStateIcon`, that is also not an icon itself but a React component that renders an icon in a container (similar to lib-ui's `StatusIcon`). As you say it's not an issue.
