### ISSUE TITLE
[BZ#1952497] Not possible to see migration plan details for in progress/Cancelled plans

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#577]
https://bugzilla.redhat.com/show_bug.cgi?id=1952497

The only way to see the contents of a mapping that is part of a plan is currently to open the plan for editing, which is not possible if the plan has ever been started. We need to find some read-only way of viewing these details from the plans table (maybe a kebab action like "review plan" that opens a modal resembling the Review step of the wizard?)

This will also be a problem with hooks that are part of a plan. An additional thing to consider here is that we may want to show any status conditions present on the mapping and hook CRs as part of this review mechanism.

**Comment by vconzola** [comment]
Mockups here: https://docs.google.com/presentation/d/1FnAK9Eh-mowADHLtDWqlD9__VQyeHserfPzeWfeg66E/edit?usp=sharing (slides 23 - 25)
