### ISSUE TITLE
[BZ#1951660] Add plan clone action for easier replacement of failed/canceled plans

### ISSUE THREAD

**Issue by mturley** [konveyor/forklift-ui#581]
https://bugzilla.redhat.com/show_bug.cgi?id=1951660

Ilanit:

> Description of problem:
> A migration plan can be edited only if it was not started yet.
> 
> In case the plan was cancelled, 
> or after a migration plan fails the plan is no longer editable.
> 
> Use cases for example:
> 1. If the failure is caused by the network/storage mapping,
> users cannot edit the plan and change the mapping. 
> 
> 2. If a plan was cancelled since users didn't set the plan correctly,
> it is not possible. Need to delete current plan and create a new one.
> 
> Can edit option be added in cases of plan failed/cancelled?

Vince:

> After meeting with Jeff, Miguel, and Mike we propose adding a "plan clone" feature first because that will be easier to implement for 2.1. If a user wants to edit a plan that has already been started and canceled, or has completed and failed, they can clone it and create a new plan which can be edited. The user will have the option of whether to include already migrated VMs in the clone (default is no). If the user chooses to include already migrated VMs in the clone the UI will alert them that they must be manually removed from the target cluster before migration or they will fail.

**Comment by mturley** [comment]
@vconzola if we still plan to do this for v2.1 we'll need to finalize the design. I assume we'll add a kebab action (what should that be called? "Clone"? "Create copy"? "Duplicate"?) which will open a modal with either a yes/no choice to include already-migrated VMs or perhaps a checklist of which VMs to include (with already-migrated defaulting to unchecked), and the warning you mention if already-migrated VMs are selected.

**Comment by vconzola** [comment]
@mturley I'd like to see some real requirements from Miguel before we jump into this.

**Comment by mturley** [comment]
Ok. I'll mark him as needinfo on the BZ.

cc @mperezco

**Comment by mturley** [comment]
Closing this because we decided not to have a plan clone feature. Instead we will consider later the impact of allowing the user to edit plans that have been run previously.

**Comment by mturley** [comment]
Resurrecting this because it is now planned for sprint 206.
