### ISSUE TITLE
Change "Create network/storage mapping" field names

### ISSUE THREAD

**Issue by apinnick** [konveyor/forklift-ui#649]
Currently, when the user creates a new network or storage mapping, the fields for selecting source and target entities are in the plural (Source datastores, Target storage classes, etc.). 

Because these dropdown lists do not support multi-selection and the use can only select one item, I recommend that the field names be changed to the singular (Source datastore).

Also, the text should be updated (Map a source datastore to a target storage class).

**Comment by apinnick** [comment]
![20210615_150828](https://user-images.githubusercontent.com/31725355/122050489-2ca63c80-cdec-11eb-9555-d67de3290bef.png)
![20210615_150747](https://user-images.githubusercontent.com/31725355/122050549-36c83b00-cdec-11eb-8fde-18054a14f14e.png)

**Comment by gildub** [comment]
@apinnick, that make sense in the case of only one mapping meanwhile there are cases of multiple mappings.

Those labels are column titles:
![Screenshot from 2021-06-17 11-38-30](https://user-images.githubusercontent.com/1901741/122372252-d1498b00-cf60-11eb-888c-905303b328bc.png)

**Comment by gildub** [comment]
Please reopen if not satisfied with answer.
