### ISSUE TITLE
Can we improve the existing route guard UI?

### ISSUE THREAD

**Issue by seanforyou23** [konveyor/forklift-ui#701]
Currently, if you're in the plan creation wizard flow and you attempt to navigate to another route/page, a native browser prompt asks to confirm before proceeding.

<img src="https://user-images.githubusercontent.com/5942899/125327937-b543ca00-e311-11eb-8bc3-2cbdb5d42f7d.png" width="400" alt="screenshot" />

It would be nice if we had a custom implementation for this so that the styles match that of the rest of the UI.

**Comment by mturley** [comment]
Note to self: even after #702, the route guard does not stop the user from closing or reloading the tab, since those operations circumvent react-router. We could address that in a future PR with clever use of the `beforeunload` event. I may follow up after this is closed to try that out.
