### ISSUE TITLE
Bug 1990851: Ability to manipulate TLS settings in UI

### ISSUE THREAD

**Issue by fbladilo** [konveyor/forklift-ui#738]
It would be ideal to get the same functionality as in forklift controller for TLS settings on UI, that is enabling/disabling , configurable cert/key locations and port , example of controller pod below : 

```
    Environment:
      POD_NAMESPACE:                 konveyor-forklift (v1:metadata.namespace)
      ROLE:                          inventory
      SECRET_NAME:                   webhook-server-secret
      API_PORT:                      8443
      API_TLS_ENABLED:               true
      API_TLS_CERTIFICATE:           /var/run/secrets/forklift-inventory-serving-cert/tls.crt
      API_TLS_KEY:                   /var/run/secrets/forklift-inventory-serving-cert/tls.key
      METRICS_PORT:                  8081
      POLICY_AGENT_URL:              https://forklift-validation.konveyor-forklift.svc.cluster.local:8181
      POLICY_AGENT_SEARCH_INTERVAL:  120
      LOG_LEVEL:                     4
```
This will certainly help cases in where we have to switch off TLS or the location for the certs/keys are different than default. @fdupont-redhat please if you have more use cases add as necessary.

**Comment by mturley** [comment]
@fbladilo should this be backported to 2.1.0? do we have a BZ?

**Comment by fbladilo** [comment]
@mturley No BZ yet , I can create a RFE for it if that sounds good? @fdupont-redhat do we want this for 2.10 or 2.2.0 target?

**Comment by mturley** [comment]
RFE sounds good!

**Comment by mturley** [comment]
Opened a 2.1.0 backport PR while I'm in here, we can close it if we want to target 2.2.0: https://github.com/konveyor/forklift-ui/pull/742

**Comment by fdupont-redhat** [comment]
It's a 2.2.0 only change.

**Comment by fbladilo** [comment]
@mturley RFE : https://bugzilla.redhat.com/show_bug.cgi?id=1990851
