### ISSUE TITLE
[BZ#1897276] Vsphere provider: Fetch and show certificate to get user validation

### ISSUE THREAD

**Issue by gildub** [konveyor/forklift-ui#833]
https://bugzilla.redhat.com/show_bug.cgi?id=1897276

The vCenter certificate can be retrieved by the Express server through a specific route and returned to the client UI in order to present it to the end user for validation.
 
The reason for the latter approach is because JavaScript on the browser side is not designed to deal with certificate (it's handled by the browsers themselves). Although we have envisaged using client side approach such as using a [native version of TLS](https://www.npmjs.com/package/node-forge) meanwhile we'd still have to handle a CORS situation.

**Comment by mturley** [comment]
This was resolved by #845.
