### ISSUE TITLE
Access Token Error Client request error: unable to verify the first certificate

### ISSUE THREAD

**Issue by dsim4** [konveyor/forklift-ui#870]
We are unable to login to the UI and we get the subject message when we login with OAuth in the forklift-ui pod.  Our OAuth is working and we can login to other endpoints.  The error seems to get generated when the login tries to authenticate with a callback page and the browser displays "Authentication error".  We are using version 2.1.0 on Openshift 4.8.

**Comment by fabiendupont** [comment]
Can you verify in the forklift-ui pod that the file `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` is present?

**Comment by dsim4** [comment]
sh-4.4$ ls -alh /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
lrwxrwxrwx. 1 root 1000770000 21 Dec 22 18:19 /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt -> ..data/service-ca.crt

**Comment by dsim4** [comment]
Closing, this issue is being worked on in another repo.

https://github.com/konveyor/forklift-operator/pull/201
